#!/usr/bin/env bash
K8S_SECRET_NAME_REGISTRY=$1
if [ -z "$K8S_SECRET_NAME_REGISTRY" ]; then
    echo "Must enter kubernetes secret name for docker config"
    exit 1
fi

kubectl create secret generic $K8S_SECRET_NAME_REGISTRY \
    --from-file=.dockerconfigjson=$HOME/.docker/config.json \
    --type=kubernetes.io/dockerconfigjson
