#!/usr/bin/env bash
INSTALL_BIN=$HOME/bin
OS=`uname | tr [A-Z] [a-z]`
OS_ARCH=`uname -m`
if [ "$OS_ARCH" == "x86_64" ]; then
    OS_ARCH="amd64"
fi

mkdir -pv $INSTALL_BIN
if [ -d ./shell ]; then
    cp -v shell/* $INSTALL_BIN
fi

if [ -d ./tools ]; then
    TOOLS_LIST=`ls -R tools/*.$OS_ARCH.$OS`
    for i in `echo $TOOLS_LIST`
    do
        TOOL_FILE=`echo $i | sed -e "s/\.$OS_ARCH\.$OS//g"`
        TOOL=`basename $TOOL_FILE`
        echo "copying TOOL: $TOOL"
        cp -v $i $INSTALL_BIN/$TOOL
    done
    
fi
chmod -v a+x $INSTALL_BIN/*
chmod -v a+x $INSTALL_BIN/*