#!/usr/bin/env bash
INSTALL_BIN=$HOME/bin
mkdir -pv $INSTALL_BIN
if [ -d ./shell ]; then
    cp -v shell/* $INSTALL_BIN
fi

if [ -d ./tools ]; then
    cp -v tools/* $INSTALL_BIN
fi
chmod -v a+x $INSTALL_BIN/*