#!/usr/bin/env bash

INSTALL_BIN=/opt/onprem-k8s-tools/bin
OS=`uname | tr [A-Z] [a-z]`
OS_ARCH=`uname -m`
if [ "$OS_ARCH" == "x86_64" ]; then
    OS_ARCH="amd64"
fi

mkdir -pv $INSTALL_BIN
if [ -d ./shell ]; then
    cp -v shell/* $INSTALL_BIN
fi

if [ -d ./tools ]; then
    cp -v tools/*.$OS_ARCH.$OS $INSTALL_BIN
fi
chmod -v a+x $INSTALL_BIN/*

if [ ! -f /etc/profile.d/onprem-k8s-tools-sysinstall.sh ]; then
    cat << PROFILE_SET > /etc/profile.d/onprem-k8s-tools-sysinstall.sh
#!/usr/bin/env bash
PATH=\$PATH:$INSTALL_BIN
export PATH
PROFILE_SET
    chmod a+x /etc/profile.d/onprem-k8s-tools-sysinstall.sh
fi